name: jaagran
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 #update
  awesome_dialog: ^1.3.2 #update

  email_validator: ^2.0.1
  modal_progress_hud: ^0.1.3
  # advance_pdf_viewer: 
  multiselect_formfield: ^0.1.5
  flutter_image_compress: ^1.0.0
  page_transition: ^1.1.7+6
  flutter_typeahead: ^2.0.0
#  smooth_star_rating: ^1.1.1
  flutter_summernote: ^0.2.3



  http: ^0.12.2 #rollback
  shared_preferences: ^0.5.12+4  #rollback
  flutter_svg: ^0.20.0-nullsafety.3  #update
  file_picker: ^2.1.6  #rollback
  video_player: ^1.0.1 #rollback
  # audioplayers:  #rollback
  chewie: ^0.12.2 #rollback
  intl: ^0.17.0 #update
  flutter_html: ^1.2.0 #rollback
  firebase_messaging: ^7.0.3 #rollback #pending
  device_info: ^2.0.0 #update

  flutter_keyboard_visibility: ^4.0.2 #rollback
  web_socket_channel: ^1.2.0 #rollback
  permission_handler: ^5.1.0+2 #rollback
  get: ^3.26.0 #update
  # agora_rtc_engine: ^3.3.2 #pending
  url_launcher: ^6.0.2 #update
  package_info: ^2.0.0 #update
  flutter_local_notifications:  #rollback
#  firebase_core: ^0.7.0 #rollback
#  firebase_crashlytics: ^0.4.0+1 #rollback
  webview_flutter: 
  get_storage: ^1.4.0
  razorpay_flutter: ^1.2.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:

    - family: caviar_dreams
      fonts:
        - asset: assets/fonts/caviar_dreams.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
